### ISSUE TITLE
Bravo Template Editor Cannot See Bravo for Power BI (User Install)

### ISSUE THREAD

**Issue by ericdomond** [sql-bi/BravoTemplateEditor#3]
Bravo (v1.0.1) installed via User Install does not appear to be recognized by the Bravo Template Editor VSCode extension. (I am also using the Microsoft Store install of Power BI Desktop, in case that helps.)

**Comment by albertospelta** [comment]
Hi @ericdomond! 
Did you get any error messages or anything like that from VSCode ? Can you provide steps to reproduce the issue ? 
Did VSCode run in restricted mode? [Restricted mode](https://code.visualstudio.com/docs/editor/workspace-trust) prevents the execution of VSCode extensions.

**Comment by ericdomond** [comment]
No error messages when installing the extension--it installed just fine.

1. Run VSCode (not restricted)
2. Run Power BI Desktop (Microsoft Store installed)
3. Load PBIX
4. Run Bravo for Power BI (User install)
5. Attach Bravo for Power BI to PBIX loaded in step 3
6. Navigate to Bravo Template Editor in VSCode, **RESULT:** "Bravo for Power BI is not running or not available on your system"

**Comment by albertospelta** [comment]
In order to allow VSCode to connect to Bravo, VSCode must be started via the template edit button in Bravo's Options panel.
This step is required as it provides VSCode with the information needed to identify the instance of Bravo running on your system.

Can you try these steps and let me know if the issue is solved?

1. Run Power BI Desktop and load a PBIX
3. Run Bravo for Power BI and attach to Power BI Desktop
5. Open Template settings in Bravo Option panel [(see docs here)](https://docs.sqlbi.com/bravo/configuration/options#templates)
6. Create a new template (see item 6 in docs)
7. Edit the template created in previous step (see item 3 in docs) - This step starts VSCode

**Comment by ericdomond** [comment]
You're right--that did work. In that case, I guess my issue can be converted to feedback. I can certainly follow this process, I just wish it wouldn't open a separate workspace when I have my Power BI/DAX workspace open in VSCode already. But I can live with this for now! Grazie, Alberto!
